Adding additional variable options for user
cloud-native-toolkit/terraform-gitops-ibm-ocs pull request #9
Opened 2022-06-06 18:48 UTC by annumberhocker

2022-09-29 20:31 UTC, timroster requested changes

2022-09-29 20:31 UTC, timroster commented on variables.tf
> +variable "osdSize" {
@annumberhocker can you set the default to 250Gi

2022-09-29 20:34 UTC, timroster commented on variables.tf
> +  default = "ibmc-vpc-block-10iops-tier"
the current default SC for the add-on is now `ibmc-vpc-block-metro-10iops-tier`

2022-09-29 22:27 UTC, timroster commented
@triceam - updates are in for the defaults now used by the add-on

2022-09-29 22:29 UTC, timroster approved these changes
lgtm

2022-09-30 21:10 UTC, annumberhocker commented
Having to restructure, so closing this pull request

2022-09-30 21:10 UTC, closed without merging